# Site settings
title: Kimerby
url: "https://kimerby.github.io"
baseurl: ""
description: >
    Kimerby Wiki

# My information
email: kimerby@gmail.com
author: kimerby
profile: 김어비
twitter_username: kimerby
github_username: kimerby
disqus_shortname: kimerby

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: kimerby
  shortname: kimerby

google_analytics:
  ua: UA-127074744-1

google_adsense:
  client: 

blame: "https://github.com/kimerby/kimerby.github.io/blame/master/_wiki"
edit: "https://github.com/kimerby/kimerby.github.io/edit/master/_wiki"
issue: "https://github.com/kimerby/kimerby.github.io/issues/new"
